### ISSUE TITLE
NDK support needed!

### ISSUE THREAD

**Issue by ugurcany** [jangrewe/gitlab-ci-android#66] opened 2021-03-25 15:25 UTC
NDK support is needed to enable native crash support explained here: https://developer.android.com/studio/build/shrink-code#native-crash-support

If we don't provide `ndk.debugSymbolLevel` in build.gradle, it gives warning regarding Android Vitals while uploading app to Google Play console.

**Comment by jangrewe** [comment] 2021-08-04 11:53
Duplicate of #15

**Closed as completed by jangrewe** 2021-08-04 11:53 UTC
